# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7uc1wg7SQ0kJZCw6TwZNtkQ92GUuk-_
"""

import time

def busqueda_binaria(arreglo, objetivo):
    izquierda = 0
    derecha = len(arreglo) - 1

    while izquierda <= derecha:
        medio = (izquierda + derecha) // 2


        if arreglo[medio] == objetivo:
            return medio

        elif arreglo[medio] < objetivo:
            izquierda = medio + 1


        else:
            derecha = medio - 1

    return -1

def ejecutar_pruebas():

    valores_n = [10, 100, 1000, 10000, 100000, 1000000]

    print("Ejecutando pruebas de Búsqueda Binaria:\n")
    print(f"{'Tamaño de n':<15} | {'Objetivo a buscar':<20} | {'Resultado (Índice)':<20} | {'Tiempo (segs)'}")
    print("-" * 80)

    for n in valores_n:

        arreglo = list(range(n))


        objetivo = n - 1


        inicio = time.perf_counter()
        indice_encontrado = busqueda_binaria(arreglo, objetivo)
        fin = time.perf_counter()

        tiempo_ejecucion = fin - inicio

        print(f"{n:<15} | {objetivo:<20} | {indice_encontrado:<20} | {tiempo_ejecucion:.7f}")


if __name__ == "__main__":
    ejecutar_pruebas()